# Generated by Django 4.2.29 on 2026-03-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('time', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['symbol', 'time'], name='api_stockre_symbol_8520f8_idx')],
            },
        ),
    ]
